# Generated by Django 5.0.7 on 2024-10-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addshora',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
