# Generated by Django 5.0.7 on 2024-11-01 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shora', '0002_addshora_receipt_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addshora',
            name='address',
        ),
        migrations.RemoveField(
            model_name='addshora',
            name='city',
        ),
        migrations.RemoveField(
            model_name='addshora',
            name='email',
        ),
        migrations.RemoveField(
            model_name='addshora',
            name='family',
        ),
        migrations.RemoveField(
            model_name='addshora',
            name='name',
        ),
        migrations.RemoveField(
            model_name='addshora',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='addshora',
            name='state',
        ),
        migrations.AddField(
            model_name='addshora',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
