# Generated by Django 5.0.7 on 2024-11-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shora', '0003_remove_addshora_address_remove_addshora_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addshora',
            name='receipt_image',
            field=models.ImageField(null=True, upload_to='receipts/'),
        ),
    ]
