# Generated by Django 5.0.7 on 2024-11-06 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shora', '0004_alter_addshora_receipt_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='addshora',
            name='receipt_image',
            field=models.ImageField(null=True, upload_to='receipts/', verbose_name='عکس فیش'),
        ),
        migrations.AlterField(
            model_name='addshora',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اطلاعات کاربر'),
        ),
    ]
