# Generated by Django 5.0.7 on 2024-11-06 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shora', '0005_alter_addshora_receipt_image_alter_addshora_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addshora',
            options={'verbose_name': 'درخواست های شورا', 'verbose_name_plural': ' درخواست های غضویت در شورا'},
        ),
    ]
