# Generated by Django 5.0.7 on 2024-11-10 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shora', '0006_alter_addshora_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان لایحه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('author', models.CharField(max_length=100, verbose_name='نام نویسنده')),
                ('category', models.CharField(choices=[('اقتصادی', 'اقتصادی'), ('اجتماعی', 'اجتماعی'), ('فرهنگی', 'فرهنگی'), ('حقوقی', 'حقوقی'), ('سایر', 'سایر')], max_length=50, verbose_name='دسته\u200cبندی')),
                ('document', models.FileField(blank=True, null=True, upload_to='bills/', verbose_name='فایل ضمیمه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اطلاعات کاربر')),
            ],
        ),
        migrations.DeleteModel(
            name='AddShora',
        ),
    ]
