# Generated by Django 5.0.7 on 2024-11-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shora', '0008_receipt_remove_bill_user_bill_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='receipt',
        ),
        migrations.AddField(
            model_name='bill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='فیش پرداختی'),
        ),
        migrations.AddField(
            model_name='bill',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
