# Generated by Django 5.0.7 on 2024-11-10 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shora', '0011_alter_bill_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddShora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_image', models.ImageField(null=True, upload_to='receipts/', verbose_name='عکس فیش')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اطلاعات کاربر')),
            ],
            options={
                'verbose_name': 'درخواست های شورا',
                'verbose_name_plural': ' درخواست های غضویت در شورا',
            },
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
