# Generated by Django 5.0.7 on 2024-11-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shora', '0013_document_delete_addshora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='receipt_image',
            field=models.ImageField(upload_to='receipts/', verbose_name='عکس فیش'),
        ),
    ]
