# Generated by Django 5.0.7 on 2024-11-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shora', '0014_alter_document_receipt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='receipt_image',
            field=models.ImageField(default='default.jpg', upload_to='receipts/', verbose_name='عکس فیش'),
        ),
    ]
