# Generated by Django 5.0.7 on 2024-11-10 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shora', '0015_alter_document_receipt_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'درخواست های شورا', 'verbose_name_plural': ' درخواست های غضویت در شورا'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='status',
        ),
        migrations.RemoveField(
            model_name='document',
            name='text',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
        migrations.RemoveField(
            model_name='document',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='document',
            name='receipt_image',
            field=models.ImageField(null=True, upload_to='receipts/', verbose_name='عکس فیش'),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اطلاعات کاربر'),
        ),
    ]
