# Generated by Django 5.0.7 on 2024-11-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shora', '0016_alter_document_options_remove_document_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'درخواست های شورا', 'verbose_name_plural': 'درخواست های عضویت در شورا'},
        ),
        migrations.AlterField(
            model_name='document',
            name='receipt_image',
            field=models.ImageField(upload_to='receipts/', verbose_name='عکس فیش'),
        ),
    ]
