# Generated by Django 5.0.7 on 2024-11-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shora', '0017_alter_document_options_alter_document_receipt_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.AlterField(
            model_name='document',
            name='receipt_image',
            field=models.ImageField(null=True, upload_to='receipts/', verbose_name='عکس فیش'),
        ),
    ]
