# Generated by Django 5.0.7 on 2024-11-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shora', '0018_alter_document_options_alter_document_receipt_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'درخواست های شورا', 'verbose_name_plural': ' درخواست های غضویت در شورا'},
        ),
    ]
