# Generated by Django 5.0.7 on 2024-11-10 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shora', '0020_rename_document_addshora'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addshora',
            options={},
        ),
        migrations.AddField(
            model_name='addshora',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='addshora',
            name='receipt_image',
            field=models.ImageField(upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='addshora',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
