# Generated by Django 5.0.7 on 2024-11-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shora', '0021_alter_addshora_options_addshora_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addshora',
            name='created_at',
        ),
    ]
