# Generated by Django 5.0.7 on 2024-11-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shora', '0026_document_delete_addshora'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='subject',
            field=models.CharField(choices=[('economic', 'اقتصادی'), ('social', 'اجتماعی'), ('Cultural', 'فرهنگی و آموزشی'), ('legal', 'حقوقی')], default='pending', max_length=10),
        ),
    ]
