# Generated by Django 5.0.7 on 2024-11-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shora', '0027_document_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='subject',
            field=models.CharField(blank=True, choices=[('economic', 'اقتصادی'), ('social', 'اجتماعی'), ('Cultural', 'فرهنگی و آموزشی'), ('legal', 'حقوقی'), ('other', 'سایر')], max_length=10, null=True),
        ),
    ]
