# Generated by Django 5.0.7 on 2024-11-11 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shora', '0030_alter_document_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(null=True)),
                ('subject', models.CharField(choices=[('Chois', 'انتحاب'), ('economic', 'اقتصادی'), ('social', 'اجتماعی'), ('Cultural', 'فرهنگی و آموزشی'), ('legal', 'حقوقی'), ('other', 'سایر')], default='Chois', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'در حال بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10)),
                ('receipt_image', models.ImageField(upload_to='documents/receipt_image/')),
                ('Letterattachment', models.FileField(upload_to='documents/Letterattachment/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
