# Generated by Django 5.1.4 on 2024-12-18 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shora', '0032_alter_assembly_subject_alter_document_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assembly',
            name='receipt_image',
        ),
        migrations.RemoveField(
            model_name='document',
            name='receipt_image',
        ),
    ]
