# Generated by Django 5.1.4 on 2024-12-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'در انتظار پاسخ'), ('answered', 'باسخ داده شد'), ('closed', 'بسته شده')], default='open', max_length=20),
        ),
    ]
