# Generated by Django 5.1.4 on 2024-12-12 12:38

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(default='0000000000', max_length=15, unique=True, verbose_name='شماره تلفن')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('family', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('state', models.CharField(blank=True, max_length=150, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='شهر')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='آدرس')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('id_card', models.ImageField(blank=True, null=True, upload_to='id_cards/', verbose_name='کارت ملی')),
                ('national_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کدملی')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='selfie/', verbose_name='عکس سلفی')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures', verbose_name='عکس پروفایل')),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='سال ساخت اکانت')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='کد وریفای')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='تایید شماره تلفن')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال سازی حساب')),
                ('is_verified', models.CharField(choices=[('1', 'وریفای نشده'), ('2', 'درحال بررسی'), ('3', 'نیاز به تغییرات'), ('4', 'وریفای شده')], default='1', max_length=30, verbose_name='وضعیت وریفای حساب')),
                ('is_staff', models.BooleanField(default=False, verbose_name='ادمین')),
            ],
            options={
                'verbose_name': 'کاربر ها',
                'verbose_name_plural': 'کاربر ها',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('message_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('users', models.ManyToManyField(blank=True, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
