# Generated by Django 5.0.7 on 2024-09-11 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('phone_number', models.CharField(default='0000000000', max_length=15, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('id_card', models.ImageField(blank=True, null=True, upload_to='id_cards/')),
                ('national_code', models.CharField(blank=True, max_length=100, null=True)),
                ('military_service_card', models.ImageField(blank=True, null=True, upload_to='military_service_cards/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures')),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verifyed', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
