# Generated by Django 5.1.4 on 2024-12-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
