# Generated by Django 5.0.7 on 2024-09-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_useraccount_is_verifyed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_verifyed',
            field=models.CharField(choices=[(1, 'Not verified'), (2, 'under review'), (3, 'need correction'), (4, 'verified')], default=1, max_length=20),
        ),
    ]
