# Generated by Django 5.0.7 on 2024-10-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_useraccount_is_verifyed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='military_service_card',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='selfie/'),
        ),
    ]
