# Generated by Django 5.0.7 on 2024-10-05 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_useraccount_military_service_card_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_verifyed',
            new_name='is_verified',
        ),
    ]
