# Generated by Django 5.0.7 on 2024-11-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_bar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bar',
        ),
    ]
