# Generated by Django 5.0.7 on 2024-11-06 19:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='family',
            field=models.CharField(max_length=100, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/', verbose_name='کارت ملی'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال سازی حساب'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='تایید شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='ادمین'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_verified',
            field=models.CharField(choices=[('1', 'وریفای نشده'), ('2', 'وریفای شده'), ('3', 'نیاز به تغییرات'), ('4', 'وریفای شده')], default='1', max_length=30, verbose_name='وضعیت وریفای حساب'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='national_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کدملی'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15, unique=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='سال ساخت اکانت'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='selfie/', verbose_name='عکس سلفی'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='state',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='کد وریفای'),
        ),
    ]
