# Generated by Django 5.0.7 on 2024-11-06 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_useraccount_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'کاربر ها', 'verbose_name_plural': 'کاربر ها'},
        ),
    ]
