# Generated by Django 5.0.7 on 2024-11-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_useraccount_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='user',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_verified',
            field=models.CharField(choices=[('1', 'وریفای نشده'), ('2', 'درحال بررسی'), ('3', 'نیاز به تغییرات'), ('4', 'وریفای شده')], default='1', max_length=30, verbose_name='وضعیت وریفای حساب'),
        ),
    ]
